version: '3'

networks:
  laravel: 

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_web
    ports:
      - "8089:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0.35-debian
    container_name: mysql_web
    restart: unless-stopped
    tty: true
    ports:
      - "4308:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: web
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_web
    volumes:
      - ./:/var/www
    ports:
      - "9008:9000"
    networks:
      - laravel